version: '3'
services:
  clojure:
    build: .
    env_file: ./env
    links:
      - db
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
      - 3001:3001
  db:
    image: mysql:8.0.16
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning_clojure_api
    